# Generated by Django 3.1 on 2020-11-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripurl',
            name='short_url',
        ),
    ]
